const { pool } = require('../../config/db');

// Department payroll cost data matching chart in Image 2
const departmentCosts = [
  { department: 'Eng', fullName: 'Engineering', cost: 1450000, percentage: 65, currency: '৳' },
  { department: 'Fin', fullName: 'Finance', cost: 1750000, percentage: 78, currency: '৳' },
  { department: 'HR', fullName: 'Human Resources', cost: 1100000, percentage: 48, currency: '৳' },
  { department: 'Prod', fullName: 'Production', cost: 2050000, percentage: 88, currency: '৳' },
  { department: 'Sales', fullName: 'Sales & Marketing', cost: 1350000, percentage: 58, currency: '৳' },
  { department: 'Admin', fullName: 'Administration', cost: 1650000, percentage: 74, currency: '৳' }
];

// Available reports list matching Image 2
const availableReports = [
  { id: 'rpt-01', name: 'Employee headcount by department', code: 'RPT-01' },
  { id: 'rpt-02', name: 'Attendance & leave report', code: 'RPT-02' },
  { id: 'rpt-03', name: 'Monthly & yearly payroll cost by department', code: 'RPT-03' },
  { id: 'rpt-04', name: 'Loan/advance outstanding & income tax deduction', code: 'RPT-04' },
  { id: 'rpt-05', name: 'Employee turnover report (joiners vs. leavers)', code: 'Added' },
  { id: 'rpt-06', name: 'NBR income tax summary (withheld vs. projected annual)', code: 'Added' }
];

// Recent export history audit trail matching Image 2
let exportHistory = [
  {
    id: 1,
    report: 'Payroll cost by department',
    format: 'PDF',
    exportedBy: 'Rahul Saha',
    date: 'Sep 10, 11:02 AM',
    timestamp: '2026-09-10T11:02:00Z'
  },
  {
    id: 2,
    report: 'NBR income tax summary',
    format: 'Excel',
    exportedBy: 'Nadia Chowdhury',
    date: 'Sep 9, 04:30 PM',
    timestamp: '2026-09-09T16:30:00Z'
  },
  {
    id: 3,
    report: 'Employee turnover report',
    format: 'Excel',
    exportedBy: 'Nadia Chowdhury',
    date: 'Sep 8, 09:15 AM',
    timestamp: '2026-09-08T09:15:00Z'
  }
];

class ReportingService {
  async getReportsList() {
    return availableReports;
  }

  async getDepartmentCosts() {
    return {
      month: 'September',
      year: 2026,
      departments: departmentCosts
    };
  }

  async getExportHistory() {
    try {
      if (pool) {
        const [rows] = await pool.query(
          'SELECT * FROM ReportExport ORDER BY exported_at DESC LIMIT 20'
        );
        if (rows && rows.length > 0) {
          return rows.map(r => ({
            id: r.id,
            report: r.report_type,
            format: r.format,
            exportedBy: r.exported_by_name || 'System Admin',
            date: new Date(r.exported_at).toLocaleDateString('en-US', {
              month: 'short',
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit'
            })
          }));
        }
      }
    } catch (err) {
      // Fallback to in-memory history
    }

    return exportHistory;
  }

  /**
   * Export report to PDF or Excel/CSV & record in audit trail
   */
  async exportReport(reportName, format = 'PDF', exportedBy = 'Nadia Chowdhury') {
    const validFormat = format.toUpperCase() === 'EXCEL' ? 'Excel' : 'PDF';
    const now = new Date();
    const formattedDate = now.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const newExportRecord = {
      id: exportHistory.length + 1,
      report: reportName,
      format: validFormat,
      exportedBy,
      date: formattedDate,
      timestamp: now.toISOString()
    };

    // Prepend to recent export history
    exportHistory.unshift(newExportRecord);

    try {
      if (pool) {
        await pool.query(
          'INSERT INTO ReportExport (report_type, format, exported_by_name, exported_at) VALUES (?, ?, ?, ?)',
          [reportName, validFormat, exportedBy, now]
        );
      }
    } catch (err) {
      // Graceful fallback
    }

    // Generate file payload
    const safeBase = reportName.replace(/[^a-zA-Z0-9]/g, '_');
    if (validFormat === 'Excel') {
      const filename = `${safeBase}_Sep2026.csv`;
      const csvData = `Report Name: ${reportName}\n` +
        `Generated By: ${exportedBy}\n` +
        `Date: ${now.toISOString()}\n\n` +
        `Department,Payroll Cost (BDT),Headcount,Status\n` +
        departmentCosts.map(d => `${d.fullName},${d.cost},30,Active`).join('\n');

      return {
        filename,
        contentType: 'text/csv; charset=utf-8',
        buffer: Buffer.from(csvData, 'utf-8'),
        historyItem: newExportRecord
      };
    } else {
      const filename = `${safeBase}_Sep2026.pdf`;
      const pdfContent = `%PDF-1.4
1 0 obj
<< /Title (${reportName})
   /Author (${exportedBy})
   /Subject (HR and Payroll Operational Report)
>>
endobj
2 0 obj
<< /Type /Catalog /Pages 3 0 R >>
endobj
3 0 obj
<< /Type /Pages /Kids [4 0 R] /Count 1 >>
endobj
4 0 obj
<< /Type /Page /Parent 3 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 7 0 R >>
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>
endobj
6 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
7 0 obj
<< /Length 500 >>
stream
BT
/F1 18 Tf
50 780 Td
(HR and Payroll MS - ${reportName}) Tj
/F2 11 Tf
0 -25 Td
(Exported by: ${exportedBy}  |  Date: ${formattedDate}  |  Format: PDF) Tj
0 -35 Td
/F1 13 Tf
(Summary Department Payroll Costs:) Tj
/F2 11 Tf
0 -20 Td
(Engineering: BDT 1,450,000) Tj
0 -18 Td
(Finance: BDT 1,750,000) Tj
0 -18 Td
(Human Resources: BDT 1,100,000) Tj
0 -18 Td
(Production: BDT 2,050,000) Tj
0 -18 Td
(Sales & Marketing: BDT 1,350,000) Tj
0 -18 Td
(Administration: BDT 1,650,000) Tj
0 -30 Td
/F2 9 Tf
(Audit Trail Verified. Generated automatically by HR and Payroll Management System.) Tj
ET
endstream
endobj
xref
0 8
0000000000 65535 f 
0000000010 00000 n 
0000000110 00000 n 
0000000160 00000 n 
0000000220 00000 n 
0000000340 00000 n 
0000000410 00000 n 
0000000475 00000 n 
trailer
<< /Size 8 /Root 2 0 R /Info 1 0 R >>
startxref
1060
%%EOF`;

      return {
        filename,
        contentType: 'application/pdf',
        buffer: Buffer.from(pdfContent, 'utf-8'),
        historyItem: newExportRecord
      };
    }
  }
}

module.exports = new ReportingService();